In [5]:
import pymysql 
import pandas as pd
import numpy as np

In [6]:
file_path = "C:/Users/Mathivadhani/OneDrive/Desktop/Mathi/traffic_stops - traffic_stops_with_vehicle_number.csv"
data = pd.read_csv(file_path)

C:\Users\Mathivadhani\AppData\Local\Temp\ipykernel_63972\2924757635.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

In [3]:
data.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,0:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,0:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,0:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,0:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,0:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305

In [4]:
data.dtypes

stop_date             object
stop_time             object
country_name          object
driver_gender         object
driver_age_raw         int64
driver_age             int64
driver_race           object
violation_raw         object
violation             object
search_conducted        bool
search_type           object
stop_outcome          object
is_arrested             bool
stop_duration         object
drugs_related_stop      bool
vehicle_number        object
dtype: object

In [5]:
data.shape

(65538, 16)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  object
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), int64(2), object(11)
memory usage: 6.7+ MB

In [7]:
data.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [8]:
data[data.isnull().any(axis=1)]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
7,2020-01-01,0:07:00,India,M,72,50,Asian,Drunk Driving,Other,False,NaN,Arrest,True,30+ Min,True,DL75KZ7835
9,2020-01-01,0:09:00,USA,M,43,21,Asian,Signal Violation,Signal,True,NaN,Warning,True,16-30 Min,False,KA79RD2271
10,2020-01-01,0:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
13,2020-01-01,0:13:00,USA,M,55,58,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,WB56XQ8946
14,2020-01-01,0:14:00,India,M,44,25,Black,Seatbelt,DUI,False,NaN,Arrest,True,30+ Min,False,GJ67CO6825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65523,2020-02-15,12:03:00,India,F,61,42,Other,Signal Violation,Other,True,NaN,Arrest,False,30+ Min,True,MH95JU7570
65529,2020-02-15,12:09:00,India,F,63,78,Black,Seatbelt,Seatbelt,True,NaN,Warning,False,0-15 Min,False,DL13IZ8119
65530,2020-02-15,12:10:00,India,M,34,72,White,Signal Violation,Seatbelt,True,NaN,Ticket,True,30+ Min,False,KA65MU9353
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

In [9]:
data.dropna(axis=1, how='all', inplace=True)

In [10]:
st=data['search_type']
st.unique()
# replace NAN values
data.fillna({
    'search_type':'No Search'
}, inplace=True)

In [12]:
data['stop_date']=pd.to_datetime(data['stop_date'], format='%Y-%m-%d')
data['stop_time']=pd.to_datetime(data['stop_time'], format='%H:%M:%S')

In [13]:
data.drop(['driver_age_raw'],axis=1,inplace=True)

In [14]:
data

,stop_date,stop_time,country_name,driver_gender,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,1900-01-01 00:00:00,Canada,M,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,1900-01-01 00:01:00,India,M,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,1900-01-01 00:02:00,USA,M,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,1900-01-01 00:03:00,Canada,M,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,1900-01-01 00:04:00,Canada,M,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,1900-01-01 12:13:00,India,F,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,1900-01-01 12:14:00,Canada,F,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,1900-01-01 12:15:00,USA,M,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,1900-01-01 12:16:00,Canada,F,63,Black,Seatbelt,Other,False,No Search,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,1900-01-01 12:17:00,USA,F,32,Other,Seatbelt,Speeding,True,No Search,Ticket,True,16-30 Min,False,UP89PT2924

In [16]:
# connect to MySQL
connection = pymysql.connect(
    host="localhost",
    user="root",
    password="Mathi@1903",
    database="policedb"
)

cursor = connection.cursor()
print("✅ Connected successfully")

✅ Connected successfully

In [17]:
cursor.execute("SHOW DATABASES")
for db in cursor.fetchall():
    print(db)

('db1',)
('information_schema',)
('mysql',)
('performance_schema',)
('policedb',)
('sakila',)
('sys',)
('world',)

In [18]:
cursor.execute("CREATE DATABASE IF NOT EXISTS policedb")
cursor.execute("USE policedb")
connection.commit()

In [19]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stop_date DATE,
    stop_time TIME,
    country_name VARCHAR(50),
    driver_gender VARCHAR(10),
    driver_age INT,
    driver_race VARCHAR(50),
    violation_raw VARCHAR(100),
    violation VARCHAR(100),
    search_conducted BOOLEAN,
    search_type VARCHAR(100),
    stop_outcome VARCHAR(100),
    is_arrested BOOLEAN,
    stop_duration VARCHAR(50),
    drugs_related_stop BOOLEAN,
    vehicle_number VARCHAR(50)
)
""")

0

In [20]:
connection.commit()
print("✅Table logs created successfully")

✅Table logs created successfully

In [21]:
data_tuples = [
    (
        row['stop_date'], row['stop_time'], row['country_name'], row['driver_gender'], row['driver_age'],
        row['driver_race'], row['violation_raw'], row['violation'], row['search_conducted'],
        row['search_type'], row['stop_outcome'], row['is_arrested'], row['stop_duration'],
        row['drugs_related_stop'], row['vehicle_number']
    )
    for _, row in data.iterrows()
]

cursor.executemany("""
    INSERT INTO logs (
        stop_date, stop_time, country_name, driver_gender, driver_age,
        driver_race, violation_raw, violation, search_conducted, search_type,
        stop_outcome, is_arrested, stop_duration, drugs_related_stop, vehicle_number
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
""", data_tuples)

connection.commit()

In [22]:
cursor.close()
connection.close()
print("✅Data inserted into SECURECHECK.logs using iterrows()")

✅Data inserted into SECURECHECK.logs using iterrows()